/**
 * HKC TRADING PLC - AUTHENTIC CHART OF ACCOUNTS (COA) MASTER
 * Direct 1:1 mapping of company's Peachtree / Sage 50 General Ledger setup.
 */

export interface AccountItem {
  id: string
  code: string
  name: string
  account_type: "Asset" | "Liability" | "Equity" | "Revenue" | "Expense"
  peachtree_type?: string
  parent_account_id: string | null
  is_active: boolean
  is_group?: boolean
}

export const COMPANY_CHART_OF_ACCOUNTS: AccountItem[] = [
  { id: "1000", code: "1000", name: "CASH", account_type: "Asset", peachtree_type: "Cash", parent_account_id: null, is_active: true, is_group: true },
  { id: "1000-01", code: "1000-01", name: "PETTY CASH", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: true },
  { id: "1000-01-01", code: "1000-01-01", name: "PETTY CASH-HEAD OFFICE", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-01", is_active: true, is_group: false },
  { id: "1000-01-02", code: "1000-01-02", name: "PETTY CASH- WHEREHOUSE", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-01", is_active: true, is_group: false },
  { id: "1000-02", code: "1000-02", name: "CASH AT BANK", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: true },
  { id: "1000-02-01", code: "1000-02-01", name: "UNB_RDB_1731816287486039", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-02", code: "1000-02-02", name: "CBE_AAB_1000243792839", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-03", code: "1000-02-03", name: "UNB_RDB_21356507165014_A", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-04", code: "1000-02-04", name: "UNB_RDB_21356507165025_B", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-042", code: "1000-02-042", name: "BANK LOAN", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-05", code: "1000-02-05", name: "UNB_RDB_ECX_1736016611485014", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-06", code: "1000-02-06", name: "CBE_AAB_ECX_1000282643697", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-07", code: "1000-02-07", name: "DGB_STB_AC_1092101637851", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-08", code: "1000-02-08", name: "CBE_FIB_AC_1000306160568", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-09", code: "1000-02-09", name: "CBO_SHB_AC_1000044369544", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-10", code: "1000-02-10", name: "ABAY_TAB_AC_1722015651591011", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-11", code: "1000-02-11", name: "CBE_RDB_AC_1000309664365", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-12", code: "1000-02-12", name: "ABAY_TAB_ECX_1720215651969012", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-13", code: "1000-02-13", name: "AIB_GFB_AC_01304807538500", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-14", code: "1000-02-14", name: "CBO_ECX_AC_1000044382087", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-15", code: "1000-02-15", name: "CBE_AC_1000191551838", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-16", code: "1000-02-16", name: "BOA_SHB_AC_23720051", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-17", code: "1000-02-17", name: "BOA_RDB_35292853", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-18", code: "1000-02-18", name: "BEB_GUB_AC_20000520346034", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-19", code: "1000-02-19", name: "CBO_SHB_ECX_1001200016831", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-20", code: "1000-02-20", name: "OIB_DRB_1074/3834909/001/3001/", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-21", code: "1000-02-21", name: "BOA_FIB_40467351/104878358", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-22", code: "1000-02-22", name: "CBE_AAB_USD_AC_1000000000462", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-23", code: "1000-02-23", name: "CBE_AAB_USD_AC_1000000000551", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-24", code: "1000-02-24", name: "CBE_R_AC_1000423376558", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-25", code: "1000-02-25", name: "ABB_R_AC_1722425651591014", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-26", code: "1000-02-26", name: "CBE_ECB_AC_1000465135224", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-27", code: "1000-02-27", name: "BUNA_CPB_AC_1599601000590", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-28", code: "1000-02-28", name: "ABB_TAB_ECX_1720215651591013", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-29", code: "1000-02-29", name: "UNB_RDB_ECX_1737116287486015", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-30", code: "1000-02-30", name: "CBO_SHB_R_100200042271", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-31", code: "1000-02-31", name: "UNB_RDB_ECX_1737116287486015", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-32", code: "1000-02-32", name: "BUB_COB_1599601000590", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-33", code: "1000-02-33", name: "CBO_CATB_AC_1059900010301", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-34", code: "1000-02-34", name: "AMB_9900003181425", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-35", code: "1000-02-35", name: "SINQB_1045373611218", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-36", code: "1000-02-36", name: "UNB_OD_AC_1732416287486028", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-37", code: "1000-02-37", name: "WEGAG", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-38", code: "1000-02-38", name: "DAB", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-39", code: "1000-02-39", name: "BOA USD-239535151", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-40", code: "1000-02-40", name: "ZEMEN 1404110452242019", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-41", code: "1000-02-41", name: "AHADU", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1000-02-42", code: "1000-02-42", name: "BLOCKED ACC UNB", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000-02", is_active: true, is_group: false },
  { id: "1100", code: "1100", name: "WORK ADVANCE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: null, is_active: true, is_group: true },
  { id: "1100-01", code: "1100-01", name: "DANIEL KEBEDE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1100", is_active: true, is_group: false },
  { id: "1100-02", code: "1100-02", name: "SEWAGEGN GETACHEW", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1100", is_active: true, is_group: false },
  { id: "1100-03", code: "1100-03", name: "PURCHASE ADVANCE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1100", is_active: true, is_group: false },
  { id: "1101", code: "1101", name: "STAFF ADVANCE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: null, is_active: true, is_group: true },
  { id: "1101-01", code: "1101-01", name: "DEJAZMACHE GEBEYEHU", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1101", is_active: true, is_group: false },
  { id: "1101-02", code: "1101-02", name: "MEKONNEN ADANE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1101", is_active: true, is_group: false },
  { id: "1101-03", code: "1101-03", name: "NIGUSE ABERA", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1101", is_active: true, is_group: false },
  { id: "1101-04", code: "1101-04", name: "LIYEW MENGISTE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1101", is_active: true, is_group: false },
  { id: "1101-05", code: "1101-05", name: "SELAMAWIT G/MEDHIN", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1101", is_active: true, is_group: false },
  { id: "1101-06", code: "1101-06", name: "TAMRAT ARASHO", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1101", is_active: true, is_group: false },
  { id: "1200", code: "1200", name: "PRE-PAYMENTS", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: null, is_active: true, is_group: true },
  { id: "1200-01", code: "1200-01", name: "PRE-PAIED WAREHOUSE RENT", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1200", is_active: true, is_group: false },
  { id: "1200-02", code: "1200-02", name: "PRE-PAID OFFICE RENT", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1200", is_active: true, is_group: false },
  { id: "1200-03", code: "1200-03", name: "PRE-PAIED INSURANCE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1200", is_active: true, is_group: false },
  { id: "1200-04", code: "1200-04", name: "DEPOSIT (ETHIO TELECOM)", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1200", is_active: true, is_group: false },
  { id: "1200-05", code: "1200-05", name: "ECX MEMBERSHIP DEPOSIT", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1200", is_active: true, is_group: false },
  { id: "1200-06", code: "1200-06", name: "ESL CONTAINER DEPOSIT", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1200", is_active: true, is_group: false },
  { id: "1200-07", code: "1200-07", name: "ERCA DEPOSIT", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1200", is_active: true, is_group: false },
  { id: "1210-08", code: "1210-08", name: "SUSPENCE ACCOUNT", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: null, is_active: true, is_group: false },
  { id: "1300", code: "1300", name: "TRADE RECIVEABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: true },
  { id: "1300-01", code: "1300-01", name: "EXPORT SALES RECIVEABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: "1300", is_active: true, is_group: false },
  { id: "1300-02", code: "1300-02", name: "TRANSPORT SERVICE RECIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: "1300", is_active: true, is_group: false },
  { id: "1300-03", code: "1300-03", name: "VET MEDICEN SALES RECIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: "1300", is_active: true, is_group: false },
  { id: "1300-04", code: "1300-04", name: "CAR SALES  RECIEVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: "1300", is_active: true, is_group: false },
  { id: "1300-05", code: "1300-05", name: "CLEANING SERVICE  RECIEVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: "1300", is_active: true, is_group: false },
  { id: "1300-08", code: "1300-08", name: "SUNDARY RECEIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: "1300", is_active: true, is_group: false },
  { id: "1300-09", code: "1300-09", name: "HOPE IMPORT & EXPORT PLC", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: "1300", is_active: true, is_group: false },
  { id: "1310", code: "1310", name: "OWNER RECEIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1320-06", code: "1320-06", name: "TAX RECEIVABE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: null, is_active: true, is_group: true },
  { id: "1320-06-01", code: "1320-06-01", name: "WITHOLD TAX RECIVABLE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1320-06", is_active: true, is_group: false },
  { id: "1320-06-02", code: "1320-06-02", name: "VAT RECIVABLE", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1320-06", is_active: true, is_group: false },
  { id: "1320-06-03", code: "1320-06-03", name: "PROFIT TAX QUARTER PREPAYMENT", account_type: "Asset", peachtree_type: "Other Current Assets", parent_account_id: "1320-06", is_active: true, is_group: false },
  { id: "1400", code: "1400", name: "STOCK IMPORT ITEMS", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: true },
  { id: "1400-01", code: "1400-01", name: "STOCK OF VETERINARY DRUG", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1400", is_active: true, is_group: false },
  { id: "1400-02", code: "1400-02", name: "STOCK OF VEHICLE", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1400", is_active: true, is_group: false },
  { id: "1410", code: "1410", name: "STOCK EXPORT ITEMS", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: true },
  { id: "1410-01", code: "1410-01", name: "STOCK OF GREEN MUNG", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1410", is_active: true, is_group: false },
  { id: "1410-02", code: "1410-02", name: "STOCK OF SOYA BEAN", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1410", is_active: true, is_group: false },
  { id: "1410-03", code: "1410-03", name: "STOCK OF REDISH SESAME SEED", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1410", is_active: true, is_group: false },
  { id: "1410-04", code: "1410-04", name: "STOCK OF SESEAM SEED", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1410", is_active: true, is_group: false },
  { id: "1410-05", code: "1410-05", name: "STOCK BLACK BEANS", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1410", is_active: true, is_group: false },
  { id: "1500", code: "1500", name: "GOOS IN TRANSIT", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: true },
  { id: "1500-09", code: "1500-09", name: "GIT LC- TF260852143701 $171600", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1500", is_active: true, is_group: false },
  { id: "1500-10", code: "1500-10", name: "GIT LC101ILSN260920003 $299999", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1500", is_active: true, is_group: false },
  { id: "1500-11", code: "1500-11", name: "GIT LC         $", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1500", is_active: true, is_group: false },
  { id: "1500-12", code: "1500-12", name: "GIT LC         $", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: "1500", is_active: true, is_group: false },
  { id: "1600", code: "1600", name: "FIXED ASSETS", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: null, is_active: true, is_group: true },
  { id: "1600-01", code: "1600-01", name: "BUILDING", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-01-1", code: "1600-01-1", name: "ACCMULATED DEP BUILDING", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-02", code: "1600-02", name: "PLANT AND MACHINERY", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-02-1", code: "1600-02-1", name: "ACC DEPR PLANT AND MACHINERY", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-03", code: "1600-03", name: "EQUIPMENT AND FURNITURE", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-03-1", code: "1600-03-1", name: "ACCM DEPREC OFFICE FUR & EQU", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-04", code: "1600-04", name: "COMPUTER", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-04-1", code: "1600-04-1", name: "ACCM DEPR COMPUTER", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-05", code: "1600-05", name: "MOTOR VEHICLE", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-05-1", code: "1600-05-1", name: "ACCMU DEPR MOTOR VEHICLE", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-06", code: "1600-06", name: "TRUCK", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-06-1", code: "1600-06-1", name: "ACC DEP TRUCK", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-07", code: "1600-07", name: "SINO TRAILER", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-07-1", code: "1600-07-1", name: "ACC DEP TRAILER", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-08", code: "1600-08", name: "OTHERS", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-08-1", code: "1600-08-1", name: "ACC DEP OTHERS", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-09", code: "1600-09", name: "WERAREHOUSE", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-09-1", code: "1600-09-1", name: "ACC. DEP. WERAREHOUSE", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1600-10", code: "1600-10", name: "RIGHT USE OF ASSET", account_type: "Asset", peachtree_type: "Fixed Assets", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "1700", code: "1700", name: "INVESTMENT", account_type: "Asset", peachtree_type: "Other Assets", parent_account_id: null, is_active: true, is_group: true },
  { id: "1700-01", code: "1700-01", name: "INVESTMENT", account_type: "Asset", peachtree_type: "Other Assets", parent_account_id: "1700", is_active: true, is_group: false },
  { id: "1700-02", code: "1700-02", name: "INVESTMENT ENAT BANK", account_type: "Asset", peachtree_type: "Other Assets", parent_account_id: "1700", is_active: true, is_group: false },
  { id: "1700-03", code: "1700-03", name: "INVESTMENT IN MEDIN CROSS BORD", account_type: "Asset", peachtree_type: "Other Assets", parent_account_id: "1700", is_active: true, is_group: false },
  { id: "1800", code: "1800", name: "CONSTRUCTION IN PROGRESS", account_type: "Asset", peachtree_type: "Other Assets", parent_account_id: null, is_active: true, is_group: true },
  { id: "1800-01", code: "1800-01", name: "CIP (FARM LAND PREPARATION )", account_type: "Asset", peachtree_type: "Other Assets", parent_account_id: "1800", is_active: true, is_group: false },
  { id: "2000", code: "2000", name: "TAX PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: true },
  { id: "2000-01", code: "2000-01", name: "INCOE TAX PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2000", is_active: true, is_group: false },
  { id: "2000-02", code: "2000-02", name: "INCOME TAX PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2000", is_active: true, is_group: false },
  { id: "2000-03", code: "2000-03", name: "PENSION TAX PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2000", is_active: true, is_group: false },
  { id: "2000-04", code: "2000-04", name: "WHT PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2000", is_active: true, is_group: false },
  { id: "2000-05", code: "2000-05", name: "VAT PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2000", is_active: true, is_group: false },
  { id: "2000-06", code: "2000-06", name: "PROFIT TAX PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2000", is_active: true, is_group: false },
  { id: "2100", code: "2100", name: "ACCRUED PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: true },
  { id: "2100-01", code: "2100-01", name: "ACCRUED TRANSPOT PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2100", is_active: true, is_group: false },
  { id: "2100-02", code: "2100-02", name: "AUDIT FEE PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2100", is_active: true, is_group: false },
  { id: "2100-03", code: "2100-03", name: "ACCRUED INTEREST PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2100", is_active: true, is_group: false },
  { id: "2100-04", code: "2100-04", name: "OUTSTANDING CHECK PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2100", is_active: true, is_group: false },
  { id: "2100-05", code: "2100-05", name: "TRANSIT FEE PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2100", is_active: true, is_group: false },
  { id: "2100-06", code: "2100-06", name: "OTHER ACCRUALS", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2100", is_active: true, is_group: false },
  { id: "2200", code: "2200", name: "SUNDARY PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: true },
  { id: "2200-01", code: "2200-01", name: "DANIEL KEBEDE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2200", is_active: true, is_group: false },
  { id: "2200-02", code: "2200-02", name: "KEBAD GIZACHEW", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2200", is_active: true, is_group: false },
  { id: "2200-03", code: "2200-03", name: "TADESSE GOBENA", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: "2200", is_active: true, is_group: false },
  { id: "2300", code: "2300", name: "BANK LOAN", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: null, is_active: true, is_group: true },
  { id: "2300-01", code: "2300-01", name: "COOPRATIVE BANK LOAN", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300", is_active: true, is_group: true },
  { id: "2300-01-01", code: "2300-01-01", name: "CBO_SHB_AC_1000200004906", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-01", is_active: true, is_group: false },
  { id: "2300-02", code: "2300-02", name: "UNITED BANK LOAN", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300", is_active: true, is_group: true },
  { id: "2300-02-01", code: "2300-02-01", name: "UNB_173ADPR24277001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-02", is_active: true, is_group: false },
  { id: "2300-02-02", code: "2300-02-02", name: "UNB_RDB_LOAN_173ADPR251990001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-02", is_active: true, is_group: false },
  { id: "2300-02-03", code: "2300-02-03", name: "UNB_RDB_LOAN_173ADPR252050001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-02", is_active: true, is_group: false },
  { id: "2300-02-04", code: "2300-02-04", name: "UNB_RDB_LOAN_173ADPR252550001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-02", is_active: true, is_group: false },
  { id: "2300-02-05", code: "2300-02-05", name: "UNB_RDB_LOAN_173ADPR253090001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-02", is_active: true, is_group: false },
  { id: "2300-02-06", code: "2300-02-06", name: "UNB_RDB_LOAN_173ADPR253350001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-02", is_active: true, is_group: false },
  { id: "2300-02-07", code: "2300-02-07", name: "UNB_RDB_LOAN_173ADPR260920001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-02", is_active: true, is_group: false },
  { id: "2300-03", code: "2300-03", name: "ABAY BANK LOAN", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300", is_active: true, is_group: true },
  { id: "2300-03-01", code: "2300-03-01", name: "ABB_REVL_233570001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-03", is_active: true, is_group: false },
  { id: "2300-03-02", code: "2300-03-02", name: "ABAY-72REVL261430502", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-03", is_active: true, is_group: false },
  { id: "2300-03-03", code: "2300-03-03", name: "ABAY-172REVL260410001", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-03", is_active: true, is_group: false },
  { id: "2300-03-04", code: "2300-03-04", name: "ABAY-", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-03", is_active: true, is_group: false },
  { id: "2300-03-05", code: "2300-03-05", name: "ABAY-", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: "2300-03", is_active: true, is_group: false },
  { id: "2400", code: "2400", name: "LEASE PAYABLE", account_type: "Liability", peachtree_type: "Long Term Liabilities", parent_account_id: null, is_active: true, is_group: false },
  { id: "3000", code: "3000", name: "EQUITY", account_type: "Equity", peachtree_type: "Equity", parent_account_id: null, is_active: true, is_group: true },
  { id: "3000-01", code: "3000-01", name: "HABTOM KEBEDE'S CAPITAL", account_type: "Equity", peachtree_type: "Equity", parent_account_id: "3000", is_active: true, is_group: false },
  { id: "3000-02", code: "3000-02", name: "OWNER WITHDRWAL", account_type: "Equity", peachtree_type: "Equity", parent_account_id: "3000", is_active: true, is_group: false },
  { id: "3000-03", code: "3000-03", name: "OWNERS CONTRIBUTION", account_type: "Equity", peachtree_type: "Equity", parent_account_id: "3000", is_active: true, is_group: false },
  { id: "3000-04", code: "3000-04", name: "RETAIND EARNINGS", account_type: "Equity", peachtree_type: "Equity", parent_account_id: "3000", is_active: true, is_group: false },
  { id: "3000-05", code: "3000-05", name: "CUSTOM VALUATION", account_type: "Equity", peachtree_type: "Equity", parent_account_id: "3000", is_active: true, is_group: false },
  { id: "3000-06", code: "3000-06", name: "PRIOR YEAR ADJUSTMENT", account_type: "Equity", peachtree_type: "Equity", parent_account_id: "3000", is_active: true, is_group: false },
  { id: "4000", code: "4000", name: "SALES", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: true },
  { id: "4000-01", code: "4000-01", name: "LOCAL SALES", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000", is_active: true, is_group: true },
  { id: "4000-01-01", code: "4000-01-01", name: "SALES OF VETERINARY DRUG", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-01", is_active: true, is_group: false },
  { id: "4000-01-02", code: "4000-01-02", name: "SALES OF TRUCK", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-01", is_active: true, is_group: false },
  { id: "4000-02", code: "4000-02", name: "EXPORT SALES", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000", is_active: true, is_group: true },
  { id: "4000-02-01", code: "4000-02-01", name: "EXPORT SALES GREEN MUNG", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-02", is_active: true, is_group: false },
  { id: "4000-02-02", code: "4000-02-02", name: "EXPORT SALES SOYA BEAN", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-02", is_active: true, is_group: false },
  { id: "4000-02-03", code: "4000-02-03", name: "EXPORT SALES REDISH SESEAM SEE", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-02", is_active: true, is_group: false },
  { id: "4000-02-04", code: "4000-02-04", name: "EXPORT SALES SESEAM SEED", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-02", is_active: true, is_group: false },
  { id: "4000-03", code: "4000-03", name: "SALES OF SERVICE", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000", is_active: true, is_group: true },
  { id: "4000-03-01", code: "4000-03-01", name: "TRANSPORT", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-03", is_active: true, is_group: false },
  { id: "4000-03-02", code: "4000-03-02", name: "CLEANING SERVICE", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-03", is_active: true, is_group: false },
  { id: "4000-03-03", code: "4000-03-03", name: "STORAGE", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-03", is_active: true, is_group: false },
  { id: "4000-03-04", code: "4000-03-04", name: "COMMISSION", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4000-03", is_active: true, is_group: false },
  { id: "4100", code: "4100", name: "FINANCIAL INCOME", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: true },
  { id: "4100-01", code: "4100-01", name: "GAIN / LOSS/  IN EXCHANGE", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4100", is_active: true, is_group: false },
  { id: "4100-02", code: "4100-02", name: "INTEREST INCOME", account_type: "Revenue", peachtree_type: "Income", parent_account_id: "4100", is_active: true, is_group: false },
  { id: "4200", code: "4200", name: "OTHER INCOME", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "5000", code: "5000", name: "COST OF GOODS IMPORT", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: true },
  { id: "5000-01", code: "5000-01", name: "COST OF VETERINARY DRUG", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "5000", is_active: true, is_group: false },
  { id: "5000-02", code: "5000-02", name: "COST OF TRUCK", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "5000", is_active: true, is_group: false },
  { id: "5010", code: "5010", name: "COST OF GOODS EXPORT", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: true },
  { id: "5010-01", code: "5010-01", name: "COST OF SALES GREEN MUNG", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "5010", is_active: true, is_group: false },
  { id: "5010-02", code: "5010-02", name: "COST OF SALES SOYA BEAN", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "5010", is_active: true, is_group: false },
  { id: "5010-03", code: "5010-03", name: "COST OF REDISH SESAME SEED", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "5010", is_active: true, is_group: false },
  { id: "5010-04", code: "5010-04", name: "COST OF SESEAM SEED", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "5010", is_active: true, is_group: false },
  { id: "6000", code: "6000", name: "SELLING AND DISTRIBUTION", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: true },
  { id: "6000-01", code: "6000-01", name: "SALARY AND BENEFIT", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-02", code: "6000-02", name: "OVER TIME", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-03", code: "6000-03", name: "CLEANING SERVICE", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-04", code: "6000-04", name: "PACKING AND BAGING", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-05", code: "6000-05", name: "COMMISSION ON PURCHASE ECX", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-06", code: "6000-06", name: "FUMIGATION", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-07", code: "6000-07", name: "WAREHOUSE RENT", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-08", code: "6000-08", name: "TRANSPORT COST", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-09", code: "6000-09", name: "ELECTRIC AND WATER", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-10", code: "6000-10", name: "LOADING UNLOADING", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-11", code: "6000-11", name: "REPAIER AND MAINTANCE", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-13", code: "6000-13", name: "COMMISSION", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-14", code: "6000-14", name: "PER-DIEM AND TRAVILLING", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-15", code: "6000-15", name: "ANNUAL INSPECTION AND REGISTR", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-16", code: "6000-16", name: "INSURANCE FOR TRUCK", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-17", code: "6000-17", name: "FREIGHT AND TRANSPORT", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-18", code: "6000-18", name: "TRANSIT SERVICE", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-19", code: "6000-19", name: "INSPECTION ,CERTEFICATE AND OT", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-21", code: "6000-21", name: "DEPREC PLANT AND MACHINERY", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "6000-22", code: "6000-22", name: "OTHER", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "8000", code: "8000", name: "ADMINISTRATION", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: null, is_active: true, is_group: true },
  { id: "8000-01", code: "8000-01", name: "SALARY AND WAGE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-02", code: "8000-02", name: "TRANSPORT ALLOWANCE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-03", code: "8000-03", name: "BONES", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-04", code: "8000-04", name: "OVER TIME", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-05", code: "8000-05", name: "HEALTH INSURANCE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-06", code: "8000-06", name: "PENSION CONTRIBUTION", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-07", code: "8000-07", name: "STATIONERY, PRINTING & OFF SUP", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-08", code: "8000-08", name: "OFFICE RENT", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-09", code: "8000-09", name: "TELEPHONE AND INTERNET", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-10", code: "8000-10", name: "PER-DIEM AND TRAVILLING", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-11", code: "8000-11", name: "FUEL AND LUBRICANTS", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-12", code: "8000-12", name: "POSTAGE AND PHOTOCOPY", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-13", code: "8000-13", name: "REPAIER AND MAINTANCE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-14", code: "8000-14", name: "UTILITY", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-15", code: "8000-15", name: "REGISTRATION AND LICENCE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-16", code: "8000-16", name: "INSURANCE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-17", code: "8000-17", name: "MEMBERSHIP, REGISTRATION ANNU", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-18", code: "8000-18", name: "AUDIT FEE & PROFFESSIONAL FEE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-19", code: "8000-19", name: "EDUCATION AND TITIUTION FEE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-20", code: "8000-20", name: "CAR RENT", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-21", code: "8000-21", name: "DONATION", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-22", code: "8000-22", name: "ENTERTAINMENT", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-23", code: "8000-23", name: "SPONSERSHIP", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-24", code: "8000-24", name: "UNCLAIMED VAT", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-25", code: "8000-25", name: "BANK SERVICE CHARGE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-26", code: "8000-26", name: "STAMP DUTY", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-27", code: "8000-27", name: "INTEREST EXPENSE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-28", code: "8000-28", name: "PENALITY", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-29", code: "8000-29", name: "DEPRECIATION EXPENSE", account_type: "Asset", peachtree_type: "Accumulated Depreciation", parent_account_id: "1600", is_active: true, is_group: false },
  { id: "8000-30", code: "8000-30", name: "MICELLANOUS", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
]

export const DEFAULT_COMPANY_SETTINGS_COA = {
  cash_account_id: "1000-01-01",
  primary_bank_account_id: "1000-02-26",
  ar_account_id: "1300-03",
  inventory_account_id: "1410-01",
  ap_account_id: "2100-06",
  tax_payable_account_id: "2000-05",
  wht_payable_account_id: "2000-04",
  income_tax_payable_account_id: "2000-02",
  pension_payable_account_id: "2000-03",
  retained_earnings_account_id: "3200",
  share_capital_account_id: "3000",
  sales_account_id: "4000-01-01",
  cogs_account_id: "6000",
  payroll_expense_account_id: "8000-01",
}

export interface GlAccountMapping {
  id: string
  label: string
  category: "Sales & Revenue" | "Purchasing & AP" | "Inventory & COGS" | "Payroll & HR" | "Expenses & Taxes" | "Banking & Treasury" | "Custom" | string
  account_id: string
  account_code: string
  account_name: string
  normal_posting: "Debit" | "Credit"
  is_system_default: boolean
  description?: string
  updated_by?: string
  created_at?: string
  updated_at?: string
}

export const DEFAULT_GL_ACCOUNT_MAPPINGS: GlAccountMapping[] = [
  // ── SALES & REVENUE (6 rules) ──
  {
    id: "sales_credit_ar",
    label: "Trade Accounts Receivable (Credit Invoicing)",
    category: "Sales & Revenue",
    account_id: "1300-03",
    account_code: "1300-03",
    account_name: "VET MEDICEN SALES RECIVABLE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Customer balance due debited upon issuing a credit sales invoice.",
  },
  {
    id: "sales_cash_clearing",
    label: "Cash / Bank (Direct Cash Sales)",
    category: "Sales & Revenue",
    account_id: "1000-02-26",
    account_code: "1000-02-26",
    account_name: "CBE_ECB_AC_1000465135224",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Operating bank/cash account debited upon immediate cash sales issue.",
  },
  {
    id: "sales_revenue_domestic",
    label: "Domestic Commercial Sales Revenue",
    category: "Sales & Revenue",
    account_id: "4000-01-01",
    account_code: "4000-01-01",
    account_name: "SALES OF VETERINARY DRUG",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Operating sales revenue recognized from domestic product sales.",
  },
  {
    id: "sales_revenue_services",
    label: "Service Revenue (Cleaning & Storage)",
    category: "Sales & Revenue",
    account_id: "4000-03-02",
    account_code: "4000-03-02",
    account_name: "CLEANING SERVICE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Revenue earned from warehouse grain cleaning, handling, and storage.",
  },
  {
    id: "sales_vat_output",
    label: "VAT Output Payable (15%)",
    category: "Sales & Revenue",
    account_id: "2000-05",
    account_code: "2000-05",
    account_name: "VAT PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Value Added Tax collected from customers, payable to tax authorities.",
  },
  {
    id: "sales_wht_withheld",
    label: "Withholding Tax Receivable Asset (Client Withheld)",
    category: "Sales & Revenue",
    account_id: "1320-06-01",
    account_code: "1320-06-01",
    account_name: "WITHOLD TAX RECIVABLE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Tax withheld by clients (2% or 30%), claimable against annual corporate tax.",
  },

  // ── PURCHASING & ACCOUNTS PAYABLE (4 rules) ──
  {
    id: "po_grni_inventory",
    label: "Inventory Stock-In-Hand (PO Goods Receipt / GRN)",
    category: "Purchasing & AP",
    account_id: "1410-01",
    account_code: "1410-01",
    account_name: "STOCK OF GREEN MUNG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Inventory asset debited when warehouse procurement receiving voucher is logged.",
  },
  {
    id: "po_grni_clearing",
    label: "Goods Received Not Invoiced / Other Accruals",
    category: "Purchasing & AP",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Clearing accrual liability credited on GRN and debited upon vendor bill receipt.",
  },
  {
    id: "ap_trade_payable",
    label: "Trade Accounts Payable (Supplier Bills)",
    category: "Purchasing & AP",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Supplier liability credited upon recording vendor purchase bill.",
  },
  {
    id: "ap_advance_prepayment",
    label: "Supplier Advance & Prepayment Asset",
    category: "Purchasing & AP",
    account_id: "1100-03",
    account_code: "1100-03",
    account_name: "PURCHASE ADVANCE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cash prepayments issued to suppliers prior to goods receipt.",
  },
  {
    id: "purchase_cash_bank",
    label: "Purchase Default Cash / Operating Bank",
    category: "Purchasing & AP",
    account_id: "1000-02-26",
    account_code: "1000-02-26",
    account_name: "CBE_ECB_AC_1000465135224",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Default operational bank account credited when paying for purchases.",
  },
  {
    id: "purchase_export_commodity",
    label: "Raw Commodity Inventory (WH1 Purchases)",
    category: "Purchasing & AP",
    account_id: "1410-01",
    account_code: "1410-01",
    account_name: "STOCK OF GREEN MUNG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Inventory asset debited for export commodity crop purchases.",
  },
  {
    id: "purchase_pharma_stock",
    label: "Pharma Inventory (WH2/WH3 Purchases)",
    category: "Purchasing & AP",
    account_id: "1400-01",
    account_code: "1400-01",
    account_name: "STOCK OF VETERINARY DRUG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Inventory asset debited for veterinary medicine purchases.",
  },
  {
    id: "purchase_packaging_bags",
    label: "Packing and Bagging Procurement",
    category: "Purchasing & AP",
    account_id: "6000-04",
    account_code: "6000-04",
    account_name: "PACKING AND BAGING",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Direct cost/asset debited for procurement of bags and packing materials.",
  },
  {
    id: "purchase_transport_freight",
    label: "Inward Freight & Logistics Procurement",
    category: "Purchasing & AP",
    account_id: "6000-08",
    account_code: "6000-08",
    account_name: "TRANSPORT COST",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Transportation and freight inward costs for purchases.",
  },
  {
    id: "purchase_office_supplies",
    label: "Office & Warehouse Supplies Procurement",
    category: "Purchasing & AP",
    account_id: "8000-07",
    account_code: "8000-07",
    account_name: "STATIONERY, PRINTING & OFF SUP",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Operating expenses debited for office and warehouse consumable supplies.",
  },
  {
    id: "purchase_general_misc",
    label: "Miscellaneous Operating Purchases",
    category: "Purchasing & AP",
    account_id: "8000-30",
    account_code: "8000-30",
    account_name: "MICELLANOUS",
    normal_posting: "Debit",
    is_system_default: true,
    description: "General operating procurement and miscellaneous business expenses.",
  },
  {
    id: "purchase_ap_credit",
    label: "Trade Accounts Payable (Supplier Credit)",
    category: "Purchasing & AP",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Supplier trade payable liability credited on credit purchase orders.",
  },

  // ── CUSTOMER & SUPPLIER PAYMENTS (3 rules) ──
  {
    id: "customer_receipt_bank",
    label: "Customer Receipt Default Bank Account",
    category: "Banking & Treasury",
    account_id: "1000-02-26",
    account_code: "1000-02-26",
    account_name: "CBE_ECB_AC_1000465135224",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Default bank account receiving customer settlement funds.",
  },
  {
    id: "supplier_payment_ap",
    label: "Supplier Payment (AP Clearing Debit)",
    category: "Purchasing & AP",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Clearing supplier liability upon issuing an AP payment voucher.",
  },
  {
    id: "supplier_payment_bank",
    label: "Supplier Payment Disbursing Bank Account",
    category: "Banking & Treasury",
    account_id: "1000-02-26",
    account_code: "1000-02-26",
    account_name: "CBE_ECB_AC_1000465135224",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Default corporate bank account used to disburse supplier payments.",
  },

  // ── INVENTORY & LOGISTICS (4 rules) ──
  {
    id: "inventory_stock_in_hand",
    label: "Commodity Stock In Hand Asset",
    category: "Inventory & COGS",
    account_id: "1410-01",
    account_code: "1410-01",
    account_name: "STOCK OF GREEN MUNG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Core balance sheet inventory asset representing warehouse commodities.",
  },
  {
    id: "cogs_stock_fulfillment",
    label: "Cost of Goods Sold (Delivery Notes / Stock Fulfillment)",
    category: "Inventory & COGS",
    account_id: "6000-04",
    account_code: "6000-04",
    account_name: "PACKING AND BAGING",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cost of sales recognized upon dispatching customer delivery note.",
  },
  {
    id: "stock_shrinkage_loss",
    label: "Physical Inventory Shrinkage / Count Loss",
    category: "Inventory & COGS",
    account_id: "6000-22",
    account_code: "6000-22",
    account_name: "OTHER",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Write-off expense debited when physical count reveals negative variance.",
  },
  {
    id: "stock_adjustment_gain",
    label: "Physical Inventory Surplus / Count Gain",
    category: "Inventory & COGS",
    account_id: "4200",
    account_code: "4200",
    account_name: "OTHER INCOME",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Gain recognized when physical audit count reveals positive stock surplus.",
  },

  // ── EXPENSES & WITHHOLDING TAX (4 rules) ──
  {
    id: "expense_default_debit",
    label: "Default General / Administrative Expense",
    category: "Expenses & Taxes",
    account_id: "8000-30",
    account_code: "8000-30",
    account_name: "MICELLANOUS",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Fallback operating expense account for operational payment vouchers.",
  },
  {
    id: "expense_vat_input",
    label: "VAT Input / Receivable Asset (15%)",
    category: "Expenses & Taxes",
    account_id: "1320-06-02",
    account_code: "1320-06-02",
    account_name: "VAT RECIVABLE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Input VAT paid on business purchases, claimable against output VAT.",
  },
  {
    id: "expense_wht_payable",
    label: "Withholding Tax Payable (Deducted from Vendors)",
    category: "Expenses & Taxes",
    account_id: "2000-04",
    account_code: "2000-04",
    account_name: "WHT PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "2% or 30% tax withheld from suppliers, payable to tax authority.",
  },
  {
    id: "expense_default_payment",
    label: "Default Petty Cash / Expense Disbursing Account",
    category: "Expenses & Taxes",
    account_id: "1000-01-01",
    account_code: "1000-01-01",
    account_name: "PETTY CASH-HEAD OFFICE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Cash account credited for head office petty cash and minor expenses.",
  },

  // ── PAYROLL & HUMAN RESOURCES (4 rules) ──
  {
    id: "payroll_gross_salary_expense",
    label: "Gross Salaries & Wages Expense",
    category: "Payroll & HR",
    account_id: "8000-01",
    account_code: "8000-01",
    account_name: "SALARY AND WAGE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Total gross compensation debited on monthly payroll accrual run.",
  },
  {
    id: "payroll_income_tax_payable",
    label: "Employee Income Tax (PAYE) Payable",
    category: "Payroll & HR",
    account_id: "2000-02",
    account_code: "2000-02",
    account_name: "INCOME TAX PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Personal income tax withheld from employee payroll, payable to government.",
  },
  {
    id: "payroll_pension_payable",
    label: "Pension Contribution Payable (7% + 11%)",
    category: "Payroll & HR",
    account_id: "2000-03",
    account_code: "2000-03",
    account_name: "PENSION TAX PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Mandatory employee (7%) and employer (11%) pension contributions payable.",
  },
  {
    id: "payroll_accrued_clearing",
    label: "Accrued Net Payroll Payable",
    category: "Payroll & HR",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Net salary liability credited on accrual, cleared upon payroll bank transfer.",
  },

  // ── BANK RECONCILIATION & FX (3 rules) ──
  {
    id: "bank_service_charge_expense",
    label: "Bank Service Charges & Fees",
    category: "Banking & Treasury",
    account_id: "8000-25",
    account_code: "8000-25",
    account_name: "BANK SERVICE CHARGE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Bank ledger fee debited during monthly bank statement reconciliation.",
  },
  {
    id: "bank_interest_income",
    label: "Bank Interest Income Earned",
    category: "Banking & Treasury",
    account_id: "4200",
    account_code: "4200",
    account_name: "OTHER INCOME",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Interest income credited during monthly bank statement reconciliation.",
  },
  {
    id: "fx_unrealized_gain_loss",
    label: "Unrealized Foreign Exchange Gain / Loss",
    category: "Banking & Treasury",
    account_id: "4200",
    account_code: "4200",
    account_name: "OTHER INCOME",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Variance account for foreign currency bank account revaluations.",
  },
]

