/**
 * HKC TRADING PLC - AUTHENTIC CHART OF ACCOUNTS (COA) MASTER
 * Direct 1:1 mapping of company's Peachtree / Sage 50 General Ledger setup.
 */

export interface AccountItem {
  id: string
  code: string
  name: string
  account_type: "Asset" | "Liability" | "Equity" | "Revenue" | "Expense"
  peachtree_type?: string
  parent_account_id: string | null
  is_active: boolean
  is_group?: boolean
}

export const COMPANY_CHART_OF_ACCOUNTS: AccountItem[] = [
  // ── CASH & BANKS (1000 series) ──
  { id: "1000", code: "1000", name: "CASH", account_type: "Asset", peachtree_type: "Cash", parent_account_id: null, is_active: true, is_group: true },
  { id: "1000-01-01", code: "1000-01-01", name: "PETTY CASH-HEAD OFFICE", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-10", code: "1000-02-10", name: "ABAY_TAB_AC_1722015651591011", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-13", code: "1000-02-13", name: "AIB_GFB_AC_01304807538500", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-17", code: "1000-02-17", name: "BOA_RDB_35292853", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-20", code: "1000-02-20", name: "OIB_DRB_1074/3834909/001/3001/", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-21", code: "1000-02-21", name: "BOA_FIB_40467351/104878358", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-26", code: "1000-02-26", name: "CBE_ECB_AC_1000465135224", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-29", code: "1000-02-29", name: "UNB_RDB_ECX_1737116287486015", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-31", code: "1000-02-31", name: "UNB_RDB_ECX_1737116287486015 (Sec)", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-33", code: "1000-02-33", name: "CBO_CATB_AC_1059900010301", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },
  { id: "1000-02-41", code: "1000-02-41", name: "AHADU", account_type: "Asset", peachtree_type: "Cash", parent_account_id: "1000", is_active: true, is_group: false },

  // ── RECEIVABLES & CURRENT ASSETS (1100–1320 series) ──
  { id: "1100-03", code: "1100-03", name: "PURCHASE ADVANCE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1101-03", code: "1101-03", name: "NIGUSE ABERA", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1101-04", code: "1101-04", name: "LIYEW MENGISTE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1200-03", code: "1200-03", name: "PRE-PAIED INSURANCE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1200-06", code: "1200-06", name: "ESL CONTAINER DEPOSIT", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1300-03", code: "1300-03", name: "VET MEDICEN SALES RECIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1300-08", code: "1300-08", name: "SUNDARY RECEIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1310", code: "1310", name: "OWNER RECEIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1320-06-01", code: "1320-06-01", name: "WITHOLD TAX RECIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },
  { id: "1320-06-02", code: "1320-06-02", name: "VAT RECIVABLE", account_type: "Asset", peachtree_type: "Accounts Receivable", parent_account_id: null, is_active: true, is_group: false },

  // ── INVENTORY & GOODS IN TRANSIT (1410–1500 series) ──
  { id: "1410-01", code: "1410-01", name: "STOCK OF GREEN MUNG", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: false },
  { id: "1410-02", code: "1410-02", name: "STOCK OF SOYA BEAN", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: false },
  { id: "1410-03", code: "1410-03", name: "STOCK OF REDISH SESAME SEED", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: false },
  { id: "1410-04", code: "1410-04", name: "STOCK OF WHITE SESAME SEED", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: false },
  { id: "1410-05", code: "1410-05", name: "STOCK OF OTHER EXPORT CROPS", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: false },
  { id: "1500-09", code: "1500-09", name: "GIT LC- TF260852143701 $171600", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: false },
  { id: "1500-10", code: "1500-10", name: "GIT LC101ILSN260920003 $299999", account_type: "Asset", peachtree_type: "Inventory", parent_account_id: null, is_active: true, is_group: false },

  // ── OTHER ASSETS / CAPITAL WIP (1800 series) ──
  { id: "1800-01", code: "1800-01", name: "CIP (FARM LAND PREPARATION )", account_type: "Asset", peachtree_type: "Other Assets", parent_account_id: null, is_active: true, is_group: false },

  // ── CURRENT LIABILITIES & TAXES (2000–2100 series) ──
  { id: "2000-02", code: "2000-02", name: "INCOME TAX PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: false },
  { id: "2000-03", code: "2000-03", name: "PENSION TAX PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: false },
  { id: "2000-04", code: "2000-04", name: "WHT PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: false },
  { id: "2000-05", code: "2000-05", name: "VAT PAYABLE", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: false },
  { id: "2100-06", code: "2100-06", name: "OTHER ACCRUALS", account_type: "Liability", peachtree_type: "Other Current Liabilities", parent_account_id: null, is_active: true, is_group: false },

  // ── EQUITY (3000 series) ──
  { id: "3000", code: "3000", name: "SHARE CAPITAL", account_type: "Equity", peachtree_type: "Equity", parent_account_id: null, is_active: true, is_group: false },
  { id: "3200", code: "3200", name: "RETAINED EARNINGS", account_type: "Equity", peachtree_type: "Equity", parent_account_id: null, is_active: true, is_group: false },

  // ── INCOME & REVENUE (4000 series) ──
  { id: "4000-01-01", code: "4000-01-01", name: "SALES OF VETERINARY DRUG", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4000-02-01", code: "4000-02-01", name: "EXPORT SALES GREEN MUNG B", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4000-02-02", code: "4000-02-02", name: "EXPORT REVENUE - SOYA BEAN", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4000-02-03", code: "4000-02-03", name: "EXPORT SALES REDISH SESAME SEED", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4000-02-04", code: "4000-02-04", name: "EXPORT REVENUE - WHITE SESAME SEED", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4000-02-05", code: "4000-02-05", name: "EXPORT SALES OTHER PULSES & CROPS", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4000-03-02", code: "4000-03-02", name: "CLEANING SERVICE", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4000-03-03", code: "4000-03-03", name: "STORAGE", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },
  { id: "4200", code: "4200", name: "OTHER INCOME", account_type: "Revenue", peachtree_type: "Income", parent_account_id: null, is_active: true, is_group: false },

  // ── COST OF SALES (5000 & 5010 series) ──
  { id: "5000-01", code: "5000-01", name: "COST OF VETERINARY DRUG", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: false },
  { id: "5010-01", code: "5010-01", name: "COST OF SALES GREEN MUNG", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: false },
  { id: "5010-02", code: "5010-02", name: "COST OF SOYA BEAN", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: false },
  { id: "5010-03", code: "5010-03", name: "COST OF SALES REDISH SESAME SEED", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: false },
  { id: "5010-04", code: "5010-04", name: "COST OF WHITE SESAME SEED", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: false },
  { id: "5010-05", code: "5010-05", name: "COST OF SALES OTHER PULSES & CROPS", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: false },

  // ── COST OF SALES & DISTRIBUTION (6000 series) ──
  { id: "6000", code: "6000", name: "SELLING AND DISTRIBUTION", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: null, is_active: true, is_group: true },
  { id: "6000-01", code: "6000-01", name: "SALARY AND BENEFIT", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-02", code: "6000-02", name: "OVER TIME", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-04", code: "6000-04", name: "PACKING AND BAGING", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-08", code: "6000-08", name: "TRANSPORT COST", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-10", code: "6000-10", name: "LOADING UNLOADING", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },
  { id: "6000-22", code: "6000-22", name: "OTHER", account_type: "Expense", peachtree_type: "Cost of Sales", parent_account_id: "6000", is_active: true, is_group: false },

  // ── ADMINISTRATIVE & GENERAL EXPENSES (8000 series) ──
  { id: "8000", code: "8000", name: "ADMINISTRATIVE & GENERAL EXPENSES", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: null, is_active: true, is_group: true },
  { id: "8000-01", code: "8000-01", name: "SALARY AND WAGE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-02", code: "8000-02", name: "TRANSPORT ALLOWANCE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-06", code: "8000-06", name: "PENSION CONTRIBUTION", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-07", code: "8000-07", name: "STATIONERY, PRINTING & OFF SUP", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-08", code: "8000-08", name: "OFFICE RENT", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-09", code: "8000-09", name: "TELEPHONE AND INTERNET", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-16", code: "8000-16", name: "INSURANCE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-18", code: "8000-18", name: "AUDIT FEE & PROFFESSIONAL FEE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-25", code: "8000-25", name: "BANK SERVICE CHARGE", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-28", code: "8000-28", name: "PENALITY", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
  { id: "8000-30", code: "8000-30", name: "MICELLANOUS", account_type: "Expense", peachtree_type: "Expenses", parent_account_id: "8000", is_active: true, is_group: false },
]

export const DEFAULT_COMPANY_SETTINGS_COA = {
  cash_account_id: "1000-01-01",
  primary_bank_account_id: "1000-02-26",
  ar_account_id: "1300-03",
  inventory_account_id: "1410-01",
  ap_account_id: "2100-06",
  tax_payable_account_id: "2000-05",
  wht_payable_account_id: "2000-04",
  income_tax_payable_account_id: "2000-02",
  pension_payable_account_id: "2000-03",
  retained_earnings_account_id: "3200",
  share_capital_account_id: "3000",
  sales_account_id: "4000-01-01",
  cogs_account_id: "5000-01",
  payroll_expense_account_id: "8000-01",
}

export interface GlAccountMapping {
  id: string
  label: string
  category:
    | "Sales & Revenue"
    | "Purchasing & AP"
    | "Inventory & COGS"
    | "Payroll & HR"
    | "Taxes & Statutory"
    | "Cash & Bank Accounts"
    | "Custom Rules"
    | string
  transaction_type?: string
  warehouse_scope?: "ALL" | "IMPORT" | "EXPORT"
  item_type?: "GREEN_MUNG" | "SESAME" | "SOYA" | "VET_PHARMA" | "ALL"
  account_id: string
  account_code: string
  account_name: string
  normal_posting: "Debit" | "Credit"
  multi_accounts?: {
    account_id: string
    account_code: string
    account_name: string
    is_default?: boolean
    default_split_percent?: number
  }[]
  is_system_default: boolean
  is_kpi_stat?: boolean
  description?: string
  updated_by?: string
  created_at?: string
  updated_at?: string
}

export const DEFAULT_GL_ACCOUNT_MAPPINGS: GlAccountMapping[] = [
  // ── SALES & REVENUE ──
  {
    id: "sales_cash_clearing",
    label: "Direct Cash / Bank Sales Settlement",
    category: "Sales & Revenue",
    transaction_type: "sales_cash_clearing",
    warehouse_scope: "ALL",
    account_id: "1000-02-26",
    account_code: "1000-02-26",
    account_name: "CBE_ECB_AC_1000465135224",
    normal_posting: "Debit",
    multi_accounts: [
      { account_id: "1000-02-26", account_code: "1000-02-26", account_name: "CBE_ECB_AC_1000465135224", is_default: true },
      { account_id: "1000-02-13", account_code: "1000-02-13", account_name: "AIB_GFB_AC_01304807538500", is_default: false },
      { account_id: "1000-02-10", account_code: "1000-02-10", account_name: "ABAY_TAB_AC_1722015651591011", is_default: false },
      { account_id: "1000-02-17", account_code: "1000-02-17", account_name: "BOA_RDB_35292853", is_default: false },
      { account_id: "1000-01-01", account_code: "1000-01-01", account_name: "PETTY CASH-HEAD OFFICE", is_default: false },
    ],
    is_system_default: true,
    description: "Operating bank or cash account debited upon immediate cash sales issue.",
  },
  {
    id: "sales_credit_ar",
    label: "Trade Accounts Receivable (Domestic Pharma Credit)",
    category: "Sales & Revenue",
    transaction_type: "sales_credit_ar",
    warehouse_scope: "IMPORT",
    item_type: "VET_PHARMA",
    account_id: "1300-03",
    account_code: "1300-03",
    account_name: "VET MEDICEN SALES RECIVABLE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Customer balance due debited upon issuing a domestic veterinary credit sales invoice.",
  },
  {
    id: "sales_credit_ar_export",
    label: "Trade Accounts Receivable (Export Sales Invoicing)",
    category: "Sales & Revenue",
    transaction_type: "sales_credit_ar_export",
    warehouse_scope: "EXPORT",
    account_id: "1300-01",
    account_code: "1300-01",
    account_name: "EXPORT SALES RECIVEABLE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Customer balance due debited upon issuing an export credit sales invoice.",
  },
  {
    id: "sales_revenue_domestic",
    label: "Domestic Commercial Sales Revenue (Pharma)",
    category: "Sales & Revenue",
    transaction_type: "sales_revenue_domestic",
    warehouse_scope: "IMPORT",
    item_type: "VET_PHARMA",
    account_id: "4000-01-01",
    account_code: "4000-01-01",
    account_name: "SALES OF VETERINARY DRUG",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Operating sales revenue recognized from domestic veterinary product sales.",
  },
  {
    id: "sales_revenue_export",
    label: "Export Green Mung Bean Sales Revenue",
    category: "Sales & Revenue",
    transaction_type: "sales_revenue_export",
    warehouse_scope: "EXPORT",
    item_type: "GREEN_MUNG",
    account_id: "4000-02-01",
    account_code: "4000-02-01",
    account_name: "EXPORT SALES GREEN MUNG B",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Operating sales revenue recognized from export Green Mung bean sales.",
  },
  {
    id: "sales_revenue_export_soya",
    label: "Export Soya Bean Sales Revenue",
    category: "Sales & Revenue",
    transaction_type: "sales_revenue_export_soya",
    warehouse_scope: "EXPORT",
    item_type: "SOYA",
    account_id: "4000-02-02",
    account_code: "4000-02-02",
    account_name: "EXPORT SALES SOYA BEAN",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Operating sales revenue recognized from export Soya Bean crop sales.",
  },
  {
    id: "sales_revenue_export_sesame",
    label: "Export Reddish Sesame Seed Sales Revenue",
    category: "Sales & Revenue",
    transaction_type: "sales_revenue_export_sesame",
    warehouse_scope: "EXPORT",
    item_type: "SESAME",
    account_id: "4000-02-03",
    account_code: "4000-02-03",
    account_name: "EXPORT SALES REDISH SESAME SEED",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Operating sales revenue recognized from export Reddish Sesame crop sales.",
  },
  {
    id: "sales_revenue_export_white_sesame",
    label: "Export White Sesame Seed Sales Revenue",
    category: "Sales & Revenue",
    transaction_type: "sales_revenue_export_white_sesame",
    warehouse_scope: "EXPORT",
    item_type: "SESAME",
    account_id: "4000-02-04",
    account_code: "4000-02-04",
    account_name: "EXPORT SALES WHITE SESAME SEED",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Operating sales revenue recognized from export White Sesame crop sales.",
  },
  {
    id: "sales_revenue_export_other",
    label: "Export Other Pulses & Crops Sales Revenue",
    category: "Sales & Revenue",
    transaction_type: "sales_revenue_export_other",
    warehouse_scope: "EXPORT",
    item_type: "ALL",
    account_id: "4000-02-05",
    account_code: "4000-02-05",
    account_name: "EXPORT SALES OTHER PULSES & CROPS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Operating sales revenue recognized from general export crops (Soybean, Pulses).",
  },
  {
    id: "sales_revenue_services",
    label: "Service Revenue (Cleaning & Storage)",
    category: "Sales & Revenue",
    transaction_type: "sales_revenue_services",
    warehouse_scope: "ALL",
    account_id: "4000-03-02",
    account_code: "4000-03-02",
    account_name: "CLEANING SERVICE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Revenue earned from warehouse grain cleaning, handling, and storage.",
  },

  // ── TAXES & STATUTORY ──
  {
    id: "sales_vat_output",
    label: "Output VAT Payable (15%)",
    category: "Taxes & Statutory",
    transaction_type: "tax_vat_output",
    warehouse_scope: "ALL",
    account_id: "2000-05",
    account_code: "2000-05",
    account_name: "VAT PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Value Added Tax collected from customers, payable to tax authorities.",
  },
  {
    id: "sales_wht_withheld",
    label: "Withholding Tax Receivable Asset (Client Withheld 2%/30%)",
    category: "Taxes & Statutory",
    transaction_type: "tax_wht_receivable",
    warehouse_scope: "ALL",
    account_id: "1320-06-01",
    account_code: "1320-06-01",
    account_name: "WITHOLD TAX RECIVABLE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Tax withheld by clients (2% or 30%), claimable against annual corporate income tax.",
  },
  {
    id: "expense_vat_input",
    label: "Input VAT Receivable Asset (15%)",
    category: "Taxes & Statutory",
    transaction_type: "tax_vat_input",
    warehouse_scope: "ALL",
    account_id: "1320-06-02",
    account_code: "1320-06-02",
    account_name: "VAT RECIVABLE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Input VAT paid on procurement and business purchases, claimable against output VAT.",
  },
  {
    id: "expense_wht_payable",
    label: "Withholding Tax Payable (Deducted from Vendors 2%/30%)",
    category: "Taxes & Statutory",
    transaction_type: "tax_wht_payable",
    warehouse_scope: "ALL",
    account_id: "2000-04",
    account_code: "2000-04",
    account_name: "WHT PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Tax withheld from suppliers/contractors, payable to the Ministry of Revenues.",
  },
  {
    id: "tax_tot_payable",
    label: "Turnover Tax (TOT 2% / 10%) Payable",
    category: "Taxes & Statutory",
    transaction_type: "tax_tot_payable",
    warehouse_scope: "ALL",
    account_id: "2000-05",
    account_code: "2000-05",
    account_name: "VAT PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Turnover tax collected on non-VAT registered sales categories.",
  },
  {
    id: "tax_income_tax_payable",
    label: "Employment Income Tax (PAYE) Payable",
    category: "Taxes & Statutory",
    transaction_type: "tax_income_tax_payable",
    warehouse_scope: "ALL",
    account_id: "2000-02",
    account_code: "2000-02",
    account_name: "INCOME TAX PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Personal income tax withheld from employee payroll, payable to government.",
  },

  // ── INVENTORY & COGS ──
  {
    id: "inventory_pharma_stock",
    label: "Veterinary / Pharma Stock In Hand Asset",
    category: "Inventory & COGS",
    transaction_type: "inventory_pharma_stock",
    warehouse_scope: "IMPORT",
    item_type: "VET_PHARMA",
    account_id: "1400-01",
    account_code: "1400-01",
    account_name: "STOCK OF VETERINARY DRUG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Balance sheet inventory asset representing veterinary and pharmaceutical stock.",
  },
  {
    id: "cogs_stock_fulfillment",
    label: "Cost of Goods Sold (Domestic Veterinary Drug)",
    category: "Inventory & COGS",
    transaction_type: "cogs_pharma",
    warehouse_scope: "IMPORT",
    item_type: "VET_PHARMA",
    account_id: "5000-01",
    account_code: "5000-01",
    account_name: "COST OF VETERINARY DRUG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cost of sales recognized upon dispatching veterinary medicines from warehouse.",
  },
  {
    id: "inventory_stock_in_hand",
    label: "Green Mung Bean Stock In Hand Asset",
    category: "Inventory & COGS",
    transaction_type: "inventory_stock_mung",
    warehouse_scope: "EXPORT",
    item_type: "GREEN_MUNG",
    account_id: "1410-01",
    account_code: "1410-01",
    account_name: "STOCK OF GREEN MUNG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Core inventory asset representing warehouse Green Mung export crop stock.",
  },
  {
    id: "inventory_soya_stock",
    label: "Soya Bean Stock In Hand Asset",
    category: "Inventory & COGS",
    transaction_type: "inventory_stock_soya",
    warehouse_scope: "EXPORT",
    item_type: "SOYA",
    account_id: "1410-02",
    account_code: "1410-02",
    account_name: "STOCK OF SOYA BEAN",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Core inventory asset representing Soya Bean crop stock in WH1.",
  },
  {
    id: "cogs_export_fulfillment",
    label: "Cost of Goods Sold (Export Green Mung)",
    category: "Inventory & COGS",
    transaction_type: "cogs_export_mung",
    warehouse_scope: "EXPORT",
    item_type: "GREEN_MUNG",
    account_id: "5010-01",
    account_code: "5010-01",
    account_name: "COST OF SALES GREEN MUNG",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cost of sales recognized upon dispatching Green Mung from WH1 Export warehouse.",
  },
  {
    id: "cogs_soya_fulfillment",
    label: "Cost of Goods Sold (Export Soya Bean)",
    category: "Inventory & COGS",
    transaction_type: "cogs_export_soya",
    warehouse_scope: "EXPORT",
    item_type: "SOYA",
    account_id: "5010-02",
    account_code: "5010-02",
    account_name: "COST OF SALES SOYA BEAN",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cost of sales recognized upon dispatching Soya Bean from WH1 Export warehouse.",
  },
  {
    id: "inventory_sesame_stock",
    label: "Reddish Sesame Seed Stock In Hand Asset",
    category: "Inventory & COGS",
    transaction_type: "inventory_stock_sesame",
    warehouse_scope: "EXPORT",
    item_type: "SESAME",
    account_id: "1410-03",
    account_code: "1410-03",
    account_name: "STOCK OF REDISH SESAME SEED",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Core inventory asset representing Reddish Sesame crop stock in WH1.",
  },
  {
    id: "cogs_sesame_fulfillment",
    label: "Cost of Goods Sold (Export Reddish Sesame)",
    category: "Inventory & COGS",
    transaction_type: "cogs_export_sesame",
    warehouse_scope: "EXPORT",
    item_type: "SESAME",
    account_id: "5010-03",
    account_code: "5010-03",
    account_name: "COST OF SALES REDISH SESAME SEED",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cost of sales recognized upon dispatching Sesame Seed from WH1 Export warehouse.",
  },
  {
    id: "inventory_white_sesame_stock",
    label: "White Sesame Seed Stock In Hand Asset",
    category: "Inventory & COGS",
    transaction_type: "inventory_stock_white_sesame",
    warehouse_scope: "EXPORT",
    item_type: "SESAME",
    account_id: "1410-04",
    account_code: "1410-04",
    account_name: "STOCK OF WHITE SESAME SEED",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Core inventory asset representing White Sesame crop stock in WH1.",
  },
  {
    id: "cogs_white_sesame_fulfillment",
    label: "Cost of Goods Sold (Export White Sesame)",
    category: "Inventory & COGS",
    transaction_type: "cogs_export_white_sesame",
    warehouse_scope: "EXPORT",
    item_type: "SESAME",
    account_id: "5010-04",
    account_code: "5010-04",
    account_name: "COST OF SALES WHITE SESAME SEED",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cost of sales recognized upon dispatching White Sesame Seed from WH1 Export warehouse.",
  },
  {
    id: "inventory_export_other_stock",
    label: "Other Pulses & Crops Stock In Hand Asset",
    category: "Inventory & COGS",
    transaction_type: "inventory_stock_other",
    warehouse_scope: "EXPORT",
    item_type: "ALL",
    account_id: "1410-05",
    account_code: "1410-05",
    account_name: "STOCK OF OTHER EXPORT CROPS",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Inventory asset for general export pulses and oilseeds.",
  },
  {
    id: "cogs_export_other_fulfillment",
    label: "Cost of Goods Sold (Export Other Pulses & Crops)",
    category: "Inventory & COGS",
    transaction_type: "cogs_export_other",
    warehouse_scope: "EXPORT",
    item_type: "ALL",
    account_id: "5010-05",
    account_code: "5010-05",
    account_name: "COST OF SALES OTHER PULSES & CROPS",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cost of sales recognized upon dispatching general pulses or crops from WH1 Export warehouse.",
  },
  {
    id: "stock_shrinkage_loss",
    label: "Physical Inventory Shrinkage / Count Loss",
    category: "Inventory & COGS",
    transaction_type: "stock_shrinkage_loss",
    warehouse_scope: "ALL",
    account_id: "6000-22",
    account_code: "6000-22",
    account_name: "OTHER",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Write-off expense debited when physical count reveals negative variance.",
  },
  {
    id: "stock_adjustment_gain",
    label: "Physical Inventory Surplus / Count Gain",
    category: "Inventory & COGS",
    transaction_type: "stock_adjustment_gain",
    warehouse_scope: "ALL",
    account_id: "4200",
    account_code: "4200",
    account_name: "OTHER INCOME",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Gain recognized when physical audit count reveals positive stock surplus.",
  },

  // ── PURCHASING & ACCOUNTS PAYABLE ──
  {
    id: "ap_trade_payable",
    label: "Trade Accounts Payable (Supplier Bills)",
    category: "Purchasing & AP",
    transaction_type: "ap_trade_payable",
    warehouse_scope: "ALL",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Supplier liability credited upon recording vendor purchase bill.",
  },
  {
    id: "po_grni_clearing",
    label: "Goods Received Not Invoiced / Other Accruals",
    category: "Purchasing & AP",
    transaction_type: "po_grni_clearing",
    warehouse_scope: "ALL",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Clearing accrual liability credited on GRN and debited upon vendor bill receipt.",
  },
  {
    id: "ap_advance_prepayment",
    label: "Supplier Advance & Prepayment Asset",
    category: "Purchasing & AP",
    transaction_type: "ap_advance_prepayment",
    warehouse_scope: "ALL",
    account_id: "1100-03",
    account_code: "1100-03",
    account_name: "PURCHASE ADVANCE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Cash prepayments issued to suppliers prior to goods receipt.",
  },
  {
    id: "supplier_payment_bank",
    label: "Supplier Payment Disbursing Bank Account",
    category: "Purchasing & AP",
    transaction_type: "supplier_payment_bank",
    warehouse_scope: "ALL",
    account_id: "1000-02-26",
    account_code: "1000-02-26",
    account_name: "CBE_ECB_AC_1000465135224",
    normal_posting: "Credit",
    multi_accounts: [
      { account_id: "1000-02-26", account_code: "1000-02-26", account_name: "CBE_ECB_AC_1000465135224", is_default: true },
      { account_id: "1000-02-13", account_code: "1000-02-13", account_name: "AIB_GFB_AC_01304807538500", is_default: false },
      { account_id: "1000-02-10", account_code: "1000-02-10", account_name: "ABAY_TAB_AC_1722015651591011", is_default: false },
    ],
    is_system_default: true,
    description: "Corporate bank accounts used to disburse supplier payments.",
  },

  // ── PAYROLL & HUMAN RESOURCES ──
  {
    id: "payroll_gross_salary_expense",
    label: "Gross Salaries & Wages Expense",
    category: "Payroll & HR",
    transaction_type: "payroll_gross_salary",
    warehouse_scope: "ALL",
    account_id: "8000-01",
    account_code: "8000-01",
    account_name: "SALARY AND WAGE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Total gross compensation debited on monthly payroll accrual run.",
  },
  {
    id: "payroll_transport_allowance",
    label: "Staff Transport & Travel Allowances",
    category: "Payroll & HR",
    transaction_type: "payroll_transport_allowance",
    warehouse_scope: "ALL",
    account_id: "8000-02",
    account_code: "8000-02",
    account_name: "TRANSPORT ALLOWANCE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Tax-free or taxable transport allowances paid to staff.",
  },
  {
    id: "payroll_employer_pension",
    label: "Employer Pension Contribution (11% Expense)",
    category: "Payroll & HR",
    transaction_type: "payroll_employer_pension",
    warehouse_scope: "ALL",
    account_id: "8000-06",
    account_code: "8000-06",
    account_name: "PENSION CONTRIBUTION",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Statutory 11% employer pension contribution expense.",
  },
  {
    id: "payroll_pension_payable",
    label: "Pension Contribution Payable (7% + 11% Total 18%)",
    category: "Payroll & HR",
    transaction_type: "payroll_pension_payable",
    warehouse_scope: "ALL",
    account_id: "2000-03",
    account_code: "2000-03",
    account_name: "PENSION TAX PAYABLE",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Combined 7% employee and 11% employer pension contributions payable to POESSA.",
  },
  {
    id: "payroll_accrued_clearing",
    label: "Accrued Net Payroll Payable",
    category: "Payroll & HR",
    transaction_type: "payroll_net_salary_clearing",
    warehouse_scope: "ALL",
    account_id: "2100-06",
    account_code: "2100-06",
    account_name: "OTHER ACCRUALS",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Net salary liability credited on accrual, cleared upon payroll bank transfer.",
  },

  // ── CASH & BANK ACCOUNTS ──
  {
    id: "customer_receipt_bank",
    label: "Customer Receipt Primary Bank Account",
    category: "Cash & Bank Accounts",
    transaction_type: "customer_receipt_bank",
    warehouse_scope: "ALL",
    account_id: "1000-02-26",
    account_code: "1000-02-26",
    account_name: "CBE_ECB_AC_1000465135224",
    normal_posting: "Debit",
    multi_accounts: [
      { account_id: "1000-02-26", account_code: "1000-02-26", account_name: "CBE_ECB_AC_1000465135224", is_default: true },
      { account_id: "1000-02-13", account_code: "1000-02-13", account_name: "AIB_GFB_AC_01304807538500", is_default: false },
      { account_id: "1000-02-10", account_code: "1000-02-10", account_name: "ABAY_TAB_AC_1722015651591011", is_default: false },
      { account_id: "1000-02-17", account_code: "1000-02-17", account_name: "BOA_RDB_35292853", is_default: false },
    ],
    is_system_default: true,
    description: "Default bank account receiving customer settlement funds.",
  },
  {
    id: "bank_service_charge_expense",
    label: "Bank Service Charges & Fees",
    category: "Cash & Bank Accounts",
    transaction_type: "bank_service_charge",
    warehouse_scope: "ALL",
    account_id: "8000-25",
    account_code: "8000-25",
    account_name: "BANK SERVICE CHARGE",
    normal_posting: "Debit",
    is_system_default: true,
    description: "Bank ledger fee debited during monthly bank statement reconciliation.",
  },
  {
    id: "bank_interest_income",
    label: "Bank Interest Income Earned",
    category: "Cash & Bank Accounts",
    transaction_type: "bank_interest_income",
    warehouse_scope: "ALL",
    account_id: "4200",
    account_code: "4200",
    account_name: "OTHER INCOME",
    normal_posting: "Credit",
    is_system_default: true,
    description: "Interest income credited during monthly bank statement reconciliation.",
  },
  // ── DASHBOARD KPI STAT MAPPINGS ──
  {
    id: "kpi_stat_operating_revenue",
    label: "KPI Stat: Operating Revenue",
    category: "Sales & Revenue",
    transaction_type: "kpi_stat",
    warehouse_scope: "ALL",
    account_id: "4000-01-01",
    account_code: "4000*",
    account_name: "Group 4000* (Operating Revenue Accounts)",
    normal_posting: "Credit",
    is_system_default: true,
    is_kpi_stat: true,
    description: "Chart of Accounts group/prefix or primary account driving Operating Revenue KPIs across Finance Overview and Control Center.",
  },
  {
    id: "kpi_stat_cost_of_goods_sold",
    label: "KPI Stat: Cost of Goods Sold (COGS)",
    category: "Inventory & COGS",
    transaction_type: "kpi_stat",
    warehouse_scope: "ALL",
    account_id: "5000-01",
    account_code: "5000*",
    account_name: "Group 5000* & 5010* (Direct Fulfillment COGS)",
    normal_posting: "Debit",
    is_system_default: true,
    is_kpi_stat: true,
    description: "Chart of Accounts group/prefix or primary account driving Cost of Goods Sold (COGS) KPIs across Finance Overview and Control Center.",
  },
  {
    id: "kpi_stat_cash_position",
    label: "KPI Stat: Liquid Cash & Bank Position",
    category: "Cash & Bank Accounts",
    transaction_type: "kpi_stat",
    warehouse_scope: "ALL",
    account_id: "1000-02-26",
    account_code: "1000*",
    account_name: "Group 1000 (Petty Cash & Bank Reserves)",
    normal_posting: "Debit",
    is_system_default: true,
    is_kpi_stat: true,
    description: "Chart of Accounts group code or primary bank account driving Liquid Cash Position KPIs on Finance Overview.",
  },
  {
    id: "kpi_stat_gross_profit",
    label: "KPI Stat: Gross Profit & Margin",
    category: "Sales & Revenue",
    transaction_type: "kpi_stat",
    warehouse_scope: "ALL",
    account_id: "FORMULA",
    account_code: "FORMULA",
    account_name: "Formula: Operating Revenue - COGS",
    normal_posting: "Credit",
    is_system_default: true,
    is_kpi_stat: true,
    description: "Derived financial surplus computed mathematically as Revenue minus COGS. Automatically reflects edits made to Revenue and COGS groups.",
  },
  {
    id: "kpi_stat_net_operating_income",
    label: "KPI Stat: Net Operating Income (EBIT)",
    category: "Sales & Revenue",
    transaction_type: "kpi_stat",
    warehouse_scope: "ALL",
    account_id: "FORMULA",
    account_code: "FORMULA",
    account_name: "Formula: Revenue - (COGS + Operating Expenses)",
    normal_posting: "Credit",
    is_system_default: true,
    is_kpi_stat: true,
    description: "Bottom-line net profit computed mathematically. Automatically reflects changes to revenue and expenses.",
  },
]

